name: Dummy Action

inputs:
  env:
    description: 'Env'
    type: string
    required: true
runs:
  dummy:
    name: Dummy
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
        - name: Dummy Step
          run: |
            echo "Dummy Run"
            echo "${{ inputs.env }}"
