name: Recursive Action
on:
  workflow_call:
    inputs:
      values:
        description: 'Array of values'
        type: string
        required: true
jobs:
  get_dependency:
    runs-on : ubuntu-latest
    outputs:
      dependency : ${{ steps.set-dependency.outputs.dependency }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: set-dependency
        run: |
          echo "dependency<<EOF" >> $GITHUB_OUTPUT
          echo "$(cat ./environments/dependency.json)" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

  execute:
    name: Execute
    runs-on: ubuntu-latest
    needs: [ get_dependency ]
    strategy:
      matrix:
        envname: ${{ fromJson(inputs.values) }}
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./github/workflow/dummy-action.yml
        with:
          env: ${{ matrix.envname }}
  
      - if: (${{ fromJson(needs.get_dependency.outputs.dependency)[matrix.envname] }} && ${{ fromJson(needs.get_dependency.outputs.dependency)[matrix.envname] }} != [])
        uses: ./.github/workflows/recursive-action.yml
        with:
          values: "${{ fromJson(needs.get_dependency.outputs.dependency)[matrix.envname] }}"

  
    
