name: Recursive Action
on:
  workflow_call:
    inputs:
      values:
        description: 'Array of values'
        type: string
        required: true
jobs:
  execute:
    name: Execute
    strategy:
      matrix:
        envname: ${{ fromJson(inputs.values) }}
      fail-fast: true

    uses: ./.github/workflows/dummy-action.yml
    with:
      env: ${{ matrix.envname }}
