name: test-action

on:
  push:
    branches: 
      - 'main'
  workflow_dispatch:

jobs:
  call-recursive-action:
    runs-on: ubuntu-latest
    steps:
    - id: initial_value
      run: |
        echo "initial_value='[\"dev\"]'" >> $GITHUB_OUTPUT
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/recursive-action.yml
      with:
        values: ${{ steps.initial_value.outputs.initial_value }}
